name: shrimp_care_mobileapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  dio: ^5.7.0
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  go_router: 13.2.3
  intl: ^0.20.2
  path_provider: ^2.1.4
  provider: ^6.1.4
  shared_preferences: ^2.0.1
  skeletonizer: ^2.0.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  build_runner: ^2.4.9
  drift_dev: ^2.26.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/core/
    - assets/others/
    - assets/disease/
    - assets/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Black.ttf
        - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
        - asset: assets/fonts/inter/Inter_18pt-ExtraBold.ttf
        - asset: assets/fonts/inter/Inter_18pt-ExtraLight.ttf
        - asset: assets/fonts/inter/Inter_18pt-Light.ttf
        - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
        - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
        - asset: assets/fonts/inter/Inter_18pt-Thin.ttf
